#!/usr/bin/with-contenv bash

# Copy config to new location so it can be mounted read-only
cp /config/rclone.conf /tmp/rclone.conf
chown $PUID:$PGID /tmp/rclone.conf
chmod +rw /tmp/rclone.conf

chown -R $PUID:$PGID /cache

while read -r l; do
  echo "Processing line: $l"

  # Parse line into array
  splitted=$(printf "%s" "$l" | xargs -n 1 printf "%s\n")
  readarray -t <<< "${splitted}"

  remote_name=${MAPFILE[0]}
  mount_point=/mnt/${MAPFILE[1]}
  params="${MAPFILE[@]:2}"

  service_name=$(echo "$remote_name" | base64)
  mkdir -p "/root/etc/s6-overlay/s6-rc.d/rclone-$service_name/dependencies.d"
  export mount_point remote_name params
  envsubst < /etc/defaults/run.sh > "/root/etc/s6-overlay/s6-rc.d/rclone-$service_name/run"
  chmod +x "/root/etc/s6-overlay/s6-rc.d/rclone-$service_name/run"
  touch  "/root/etc/s6-overlay/s6-rc.d/rclone-$service_name/dependencies.d/init-services"
  echo "longrun" > "/root/etc/s6-overlay/s6-rc.d/rclone-$service_name/type"
done </config/config.txt

echo "Done."
