name: Build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 5 * * *' # every day 5am

env:
  IMAGE_NAME: ${{ github.repository }}
  VERSION: ""  # Filled later
  TAGS: ""     # Filled later

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
    - name: shellcheck
      run: find root/ -type f | xargs shellcheck -s bash -e SC1008

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: pagdot
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch VERSION
        run: "bash .github/workflows/fetch_vers.sh"

      - name: Generate TAGS
        run: "bash .github/workflows/gen_tags.sh"

      - name: Build and push containers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm,linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.TAGS }}
